[workspace]
resolver = "2"
members = [
    "ui",
    "mobile",
    "api",
]

[workspace.dependencies]
dioxus = { version = "0.7.4" }

# workspace
ui = { path = "ui" }
api = { path = "api" }
mobile = { path = "mobile" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
